package scanner

import (
	"testing"
)

func TestIsTestFile(t *testing.T) {
	tests := []struct {
		relPath string
		want    bool
	}{
		// Suffix-based detection
		{"internal/handler_test.go", true},
		{"src/component.test.tsx", true},
		{"src/component.test.ts", true},
		{"lib/utils.test.js", true},
		{"lib/utils.test.jsx", true},
		{"src/handler.spec.ts", true},
		{"src/handler.spec.tsx", true},
		{"src/handler.spec.js", true},
		{"src/handler.spec.jsx", true},
		{"tests/model_test.py", true},
		{"src/parser_test.rs", true},

		// Prefix-based detection (Python convention)
		{"test_helpers.py", true},
		{"utils/test_db.py", true},

		// Directory-based detection
		{"__tests__/foo.ts", true},
		{"test/helper.go", true},
		{"tests/integration/run.py", true},
		{"spec/models/user.rb", true},

		// Negative cases — should NOT be test files
		{"internal/handler.go", false},
		{"src/testing.go", false},
		{"src/contest.ts", false},
		{"internal/testutil/helper.go", false}, // "testutil" is not in testDirs
		{"src/attest.js", false},
		{"main.go", false},
	}

	for _, tt := range tests {
		t.Run(tt.relPath, func(t *testing.T) {
			got := isTestFile(tt.relPath)
			if got != tt.want {
				t.Errorf("isTestFile(%q) = %v, want %v", tt.relPath, got, tt.want)
			}
		})
	}
}

func TestIsGeneratedFile(t *testing.T) {
	tests := []struct {
		name    string
		content string
		want    bool
	}{
		{
			"protoc generated Go",
			"// Code generated by protoc-gen-go. DO NOT EDIT.\npackage pb\n",
			true,
		},
		{
			"DO NOT EDIT marker",
			"// DO NOT EDIT - auto generated\npackage foo\n",
			true,
		},
		{
			"@generated annotation",
			"/** @generated */\nimport React from 'react';\n",
			true,
		},
		{
			"normal source file",
			"package main\n\nfunc main() {\n\tfmt.Println(\"hello\")\n}\n",
			false,
		},
		{
			"file mentioning edit in normal context",
			"// This file lets users edit their profiles\npackage user\n",
			false,
		},
		{
			"empty file",
			"",
			false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := isGeneratedFile([]byte(tt.content))
			if got != tt.want {
				t.Errorf("isGeneratedFile(%q) = %v, want %v", tt.name, got, tt.want)
			}
		})
	}
}

func TestIsBarrelFile(t *testing.T) {
	tests := []struct {
		name     string
		language string
		content  string
		want     bool
	}{
		{
			"pure re-exports",
			"TypeScript",
			"export { Foo } from './foo';\nexport { Bar } from './bar';\n",
			true,
		},
		{
			"re-exports with imports",
			"TypeScript",
			"import { internal } from './internal';\nexport { Foo } from './foo';\n",
			true,
		},
		{
			"barrel with comments",
			"TypeScript",
			"// Public API\nexport { Foo } from './foo';\nexport { Bar } from './bar';\n",
			true,
		},
		{
			"barrel with use strict",
			"JavaScript",
			"\"use strict\";\nexport { Foo } from './foo';\n",
			true,
		},
		{
			"file with function definition — not barrel",
			"TypeScript",
			"export { Foo } from './foo';\n\nfunction helper() { return 1; }\n",
			false,
		},
		{
			"file with class — not barrel",
			"TypeScript",
			"export class Foo { bar() {} }\n",
			false,
		},
		{
			"Go file — barrel detection disabled",
			"Go",
			"package main\n",
			false,
		},
		{
			"empty TS file — no exports",
			"TypeScript",
			"// nothing here\n",
			false,
		},
		{
			"barrel with block comment",
			"TypeScript",
			"/* Module exports */\nexport { A } from './a';\nexport { B } from './b';\n",
			true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := isBarrelFile(tt.language, []byte(tt.content))
			if got != tt.want {
				t.Errorf("isBarrelFile(%q, %q) = %v, want %v", tt.language, tt.name, got, tt.want)
			}
		})
	}
}

func TestClassifyFile(t *testing.T) {
	tests := []struct {
		name       string
		entry      FileEntry
		content    string
		wantSkip   bool
		wantReason string
	}{
		{
			"test file",
			FileEntry{RelPath: "pkg/handler_test.go", Language: "Go"},
			"package pkg\n\nfunc TestHandler(t *testing.T) {}\n",
			true, "test",
		},
		{
			"generated file",
			FileEntry{RelPath: "api/pb/service.pb.go", Language: "Go"},
			"// Code generated by protoc-gen-go. DO NOT EDIT.\npackage pb\n",
			true, "generated",
		},
		{
			"barrel file",
			FileEntry{RelPath: "src/index.ts", Language: "TypeScript"},
			"export { Foo } from './foo';\nexport { Bar } from './bar';\n",
			true, "barrel",
		},
		{
			"normal source file",
			FileEntry{RelPath: "internal/scanner/walker.go", Language: "Go"},
			"package scanner\n\nfunc Walk() {}\n",
			false, "",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			entry := tt.entry
			ClassifyFile(&entry, []byte(tt.content))
			if entry.SkipAnalysis != tt.wantSkip {
				t.Errorf("ClassifyFile: SkipAnalysis = %v, want %v", entry.SkipAnalysis, tt.wantSkip)
			}
			if entry.SkipReason != tt.wantReason {
				t.Errorf("ClassifyFile: SkipReason = %q, want %q", entry.SkipReason, tt.wantReason)
			}
		})
	}
}

func TestClassifyFilePriority(t *testing.T) {
	// A test file that is also generated should be classified as "test" (first check wins)
	entry := FileEntry{RelPath: "test/generated_test.go", Language: "Go"}
	content := []byte("// Code generated by foo. DO NOT EDIT.\npackage test\n")
	ClassifyFile(&entry, content)

	if !entry.SkipAnalysis {
		t.Error("expected SkipAnalysis = true")
	}
	if entry.SkipReason != "test" {
		t.Errorf("expected SkipReason = 'test', got %q (test check should take priority)", entry.SkipReason)
	}
}
